name: Python Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deploypages.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run Python script
        run: |
          pipenv run python midjourney.py
          cat midjourney.html
          ls -l midjourney.html
          pwd

      - name: Upload HTML artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deploypages
        uses: actions/deploy-pages@v2
