name: Python Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install pipenv
      run: |
        pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: pipenv install

    - name: Run Python script
      run: |
        pipenv run python midjourney.py
        cat midjourney.html

    - name: Upload HTML artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: midjourney.html
        name: html-file

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        artifact-name: html-file
        target-branch: gh-pages

