name: Python Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install pipenv
      run: |
        pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: pipenv install

    - name: Run Python script
      run: pipenv run python midjourney.py

    - name: Commit and push HTML file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git checkout gh-pages
        git add -f midjourney.html
        git commit -m "Update midjourney.html"
        git push -u origin gh-pages
